import { ReactNode } from "react";
import Head from "next/head";
import Navbar from "../widgets/Navbar";
import { Theme } from "@/lib/types";

interface LayoutProps {
    children?: ReactNode;
    theme?: Theme
}

export default function Layout({ children, theme = Theme.Light }: LayoutProps) {
    return (
        <>
            <Head>
                <title>HTM</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Navbar theme={theme}/>
                {children}
            </main>
        </>
    );
}
